providers = ["python"]

[phases.install]
cmds = [
  "pip install -r price_tracker/requirements.txt",
  "playwright install --with-deps chromium"
]

[phases.build]
cmds = ["cd price_tracker && python manage.py collectstatic --no-input"]
