# Generated by Django 6.0.4 on 2026-04-07 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('base_url', models.URLField()),
                ('list_url', models.URLField(blank=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('source_url', models.TextField()),
                ('external_id', models.CharField(db_index=True, max_length=500)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('local_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_tracked', models.BooleanField(db_index=True, default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tracker.marketplacesource')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_price_text', models.CharField(blank=True, max_length=100)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='tracker.marketplacesource')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='tracker.product')),
            ],
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(default='test@example.com', max_length=254)),
                ('notified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tracker.product')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_logs', to='tracker.product')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_logs', to='tracker.marketplacesource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
